### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by chapdodf** [lucioerlan/Telegram-Bot#1]
**Estou tentando  fazer um bot no TELEGRAM e peguei sua SOURCE como modelo ** , Mas estou recebendo o seguinte erro  
**error: [polling_error] {"code":"EFATAL","message":"EFATAL: Telegram Bot Token not provided!"}** 
Queria uma ajuda para arrumar esse problema  muito obrigado!

**Comment by lucioerlan** [comment]
Olá chapdof, Você criou o arquivo .env, com o token gerado pelo bot father?

**Comment by chapdodf** [comment]
sim criei.

**Comment by lucioerlan** [comment]
Rode com o Docker, coloque o token do bot father em environment, em seguida rode docker-compose up -d
